on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  call-build:
    uses: ./OnPush.yml

  release:
    name: Create Release
    runs-on: windows-latest

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  upload:
    name: Upload Release
    needs: [call-build, release]
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Debug, RelWithDebInfo, Release, MinSizeRel]
        compiler: [MSVC]

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: libwthread-${{runner.os}}-${{runner.arch}}-${{matrix.compiler}}-${{matrix.build_type}}-${{github.sha}}
      
      - name: Package
        working-directory: ${{github.workspace}}
        run: tar -zcvf package.tar.gz ./lib/* ./bin/* ./include/WThread.hpp ./include/Macros.hpp ./README.md ./LICENSE

      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./package.tar.gz
          asset_name: libwthread-${{runner.os}}-${{runner.arch}}-${{matrix.compiler}}-${{matrix.build_type}}-${{github.ref}}.tar.gz
          asset_content_type: application/gzip